# coding: utf-8

"""
    ComplyCo SDK

    A REST API for working with ComplyCo data.

    The version of the OpenAPI document: 1.0.0
    Contact: support@complyco.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from setuptools import setup, find_packages  # noqa: H301

# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools
NAME = "complyco-sdk"
VERSION = "1.0.0"
PYTHON_REQUIRES = ">=3.9"
REQUIRES = [
    "urllib3 >= 2.5.0",
    "python-dateutil",
    "pydantic >= 2",
    "typing-extensions >= 4.7.1",
]

setup(
    name=NAME,
    version=VERSION,
    description="ComplyCo SDK",
    author="ComplyCo Support",
    author_email="support@complyco.com",
    url="",
    keywords=["OpenAPI", "OpenAPI-Generator", "ComplyCo SDK"],
    install_requires=REQUIRES,
    packages=find_packages(exclude=["test", "tests"]),
    include_package_data=True,
    long_description_content_type='text/markdown',
    long_description="""\
    A REST API for working with ComplyCo data.
    """,  # noqa: E501
    package_data={"complyco": ["py.typed"]},
)
