<?php
/**
 * CanceltaskResponseBodyTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  ComplyCo
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * ComplyCo SDK
 *
 * A REST API for working with ComplyCo data.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@complyco.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.3.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace ComplyCo\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * CanceltaskResponseBodyTest Class Doc Comment
 *
 * @category    Class
 * @description CanceltaskResponseBody
 * @package     ComplyCo
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class CanceltaskResponseBodyTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "CanceltaskResponseBody"
     */
    public function testCanceltaskResponseBody()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "message"
     */
    public function testPropertyMessage()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
