<?php
/**
 * GettaskResponseBodyTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  ComplyCo
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * ComplyCo SDK
 *
 * A REST API for working with ComplyCo data.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@complyco.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.3.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace ComplyCo\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * GettaskResponseBodyTest Class Doc Comment
 *
 * @category    Class
 * @description GettaskResponseBody
 * @package     ComplyCo
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class GettaskResponseBodyTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "GettaskResponseBody"
     */
    public function testGettaskResponseBody()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "cancelled_at"
     */
    public function testPropertyCancelledAt()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "completed_at"
     */
    public function testPropertyCompletedAt()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "document_name"
     */
    public function testPropertyDocumentName()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "expires_at"
     */
    public function testPropertyExpiresAt()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "file_url"
     */
    public function testPropertyFileUrl()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "identity_email"
     */
    public function testPropertyIdentityEmail()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "identity_id"
     */
    public function testPropertyIdentityId()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "message"
     */
    public function testPropertyMessage()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "scroll_required"
     */
    public function testPropertyScrollRequired()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "signature_required"
     */
    public function testPropertySignatureRequired()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
