<?php
/**
 * TaskApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  ComplyCo
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * ComplyCo SDK
 *
 * A REST API for working with ComplyCo data.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@complyco.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.3.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace ComplyCo\Test\Api;

use \ComplyCo\Configuration;
use \ComplyCo\ApiException;
use \ComplyCo\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * TaskApiTest Class Doc Comment
 *
 * @category Class
 * @package  ComplyCo
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class TaskApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for cancelTask
     *
     * Cancel task..
     *
     */
    public function testCancelTask()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for extendTaskExpiry
     *
     * Extend task expiry date..
     *
     */
    public function testExtendTaskExpiry()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getTask
     *
     * Get task..
     *
     */
    public function testGetTask()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getTasks
     *
     * Get all tasks..
     *
     */
    public function testGetTasks()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postTask
     *
     * Create document consent task..
     *
     */
    public function testPostTask()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
