# coding: utf-8

"""
    ComplyCo SDK

    A REST API for working with ComplyCo data.

    The version of the OpenAPI document: 1.0.0
    Contact: support@complyco.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from complyco.models.gettask_response_body import GettaskResponseBody

class TestGettaskResponseBody(unittest.TestCase):
    """GettaskResponseBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GettaskResponseBody:
        """Test GettaskResponseBody
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GettaskResponseBody`
        """
        model = GettaskResponseBody()
        if include_optional:
            return GettaskResponseBody(
                cancelled_at = '',
                completed_at = '',
                document_name = '',
                expires_at = '',
                file_url = '',
                identity_email = '',
                identity_id = '',
                message = '',
                scroll_required = True,
                signature_required = True
            )
        else:
            return GettaskResponseBody(
        )
        """

    def testGettaskResponseBody(self):
        """Test GettaskResponseBody"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
