# coding: utf-8

"""
    ComplyCo SDK

    A REST API for working with ComplyCo data.

    The version of the OpenAPI document: 1.0.0
    Contact: support@complyco.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from complyco.api.task_api import TaskApi


class TestTaskApi(unittest.TestCase):
    """TaskApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TaskApi()

    def tearDown(self) -> None:
        pass

    def test_cancel_task(self) -> None:
        """Test case for cancel_task

        Cancel task.
        """
        pass

    def test_extend_task_expiry(self) -> None:
        """Test case for extend_task_expiry

        Extend task expiry date.
        """
        pass

    def test_get_task(self) -> None:
        """Test case for get_task

        Get task.
        """
        pass

    def test_get_tasks(self) -> None:
        """Test case for get_tasks

        Get all tasks.
        """
        pass

    def test_post_task(self) -> None:
        """Test case for post_task

        Create document consent task.
        """
        pass


if __name__ == '__main__':
    unittest.main()
